# Domain: Artists
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: payments
  description: Domain encompassing all payment-related systems and services
spec:
  owner: _all_account_users


