# Domain: Artists
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: payments
  description: Domain encompassing all payment-related systems and services
spec:
  owner: _all_account_users


--- 
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order-management
  description: Handles all order processing and tracking
spec:
  owner: _all_account_users
  domain: payments


---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: Service responsible for processing orders
spec:
  type: service
  lifecycle: production
  owner: _all_account_users
  system: order-management


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-api
  description: API for order processing
spec:
  type: openapi
  lifecycle: production
  owner: order-team
  system: order-management
  definition: https://api.example.com/order/openapi.yaml

  
