site_name: 'Example Documentation'
repo_url: https://github.com/adiyaar24/samplebackstage
edit_uri: https://github.com/adiyaar24/samplebackstage/edit/main/docs/index.md
docs_dir: docs
nav:
  - Home: index.md
  - Hello: nav2.md
plugins:
  - techdocs-core
